% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Mar-2022 10:56:07
%  MATLAB version: 9.10.0.1669831 (R2021a) Update 2
% -------------------------------------------------------------------
                                         

ErrCodeEl = Simulink.Parameter;
ErrCodeEl.Value = 2;
ErrCodeEl.HasCoderInfo = false;
ErrCodeEl.Description = '';
ErrCodeEl.DataType = 'uint16';
ErrCodeEl.Min = [];
ErrCodeEl.Max = [];
ErrCodeEl.DocUnits = '';

ErrCodeIn = Simulink.Parameter;
ErrCodeIn.Value = 1;
ErrCodeIn.HasCoderInfo = false;
ErrCodeIn.Description = '';
ErrCodeIn.DataType = 'uint16';
ErrCodeIn.Min = [];
ErrCodeIn.Max = [];
ErrCodeIn.DocUnits = '';

ErrCodeOut = Simulink.Parameter;
ErrCodeOut.Value = 3;
ErrCodeOut.HasCoderInfo = false;
ErrCodeOut.Description = '';
ErrCodeOut.DataType = 'uint16';
ErrCodeOut.Min = [];
ErrCodeOut.Max = [];
ErrCodeOut.DocUnits = '';

ErrVarCheckIn = Simulink.Parameter;
ErrVarCheckIn.Value = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0];
ErrVarCheckIn.HasCoderInfo = false;
ErrVarCheckIn.Description = '';
ErrVarCheckIn.DataType = 'auto';
ErrVarCheckIn.Min = [];
ErrVarCheckIn.Max = [];
ErrVarCheckIn.DocUnits = '';

ErrVarCheckOut = Simulink.Parameter;
ErrVarCheckOut.Value = [0; 0; 0];
ErrVarCheckOut.HasCoderInfo = false;
ErrVarCheckOut.Description = '';
ErrVarCheckOut.DataType = 'auto';
ErrVarCheckOut.Min = [];
ErrVarCheckOut.Max = [];
ErrVarCheckOut.DocUnits = '';

ErrVarEl = Simulink.Parameter;
ErrVarEl.Value = 0;
ErrVarEl.HasCoderInfo = false;
ErrVarEl.Description = '';
ErrVarEl.DataType = 'auto';
ErrVarEl.Min = [];
ErrVarEl.Max = [];
ErrVarEl.DocUnits = '';

IPP_RefAltitude = Simulink.Parameter;
IPP_RefAltitude.Value = 450000;
IPP_RefAltitude.HasCoderInfo = false;
IPP_RefAltitude.Description = '';
IPP_RefAltitude.DataType = 'auto';
IPP_RefAltitude.Min = [];
IPP_RefAltitude.Max = [];
IPP_RefAltitude.DocUnits = '';

LTd = Simulink.Parameter;
LTd.Value = 14;
LTd.HasCoderInfo = false;
LTd.Description = '';
LTd.DataType = 'auto';
LTd.Min = [];
LTd.Max = [];
LTd.DocUnits = '';

NoErr = Simulink.Parameter;
NoErr.Value = 0;
NoErr.HasCoderInfo = false;
NoErr.Description = '';
NoErr.DataType = 'uint16';
NoErr.Min = [];
NoErr.Max = [];
NoErr.DocUnits = '';

Pf1 = Simulink.Parameter;
Pf1.Value = 0.4;
Pf1.HasCoderInfo = false;
Pf1.Description = '';
Pf1.DataType = 'auto';
Pf1.Min = [];
Pf1.Max = [];
Pf1.DocUnits = '';

RangeLwEl = Simulink.Parameter;
RangeLwEl.Value = 0;
RangeLwEl.HasCoderInfo = false;
RangeLwEl.Description = '';
RangeLwEl.DataType = 'auto';
RangeLwEl.Min = [];
RangeLwEl.Max = [];
RangeLwEl.DocUnits = '';

RangeLwIn = Simulink.Parameter;
RangeLwIn.Value = [-1.0E+12; -1.0E+12; -1.0E+12; -1.0E+12; -1.0E+12; -1.0E+12; ...
                   -1.0E+12; -1.0E+12; -1.0E+12; -1.0E+12; -1.0E+12; -1.0E+12; ...
                   ];
RangeLwIn.HasCoderInfo = false;
RangeLwIn.Description = '';
RangeLwIn.DataType = 'auto';
RangeLwIn.Min = [];
RangeLwIn.Max = [];
RangeLwIn.DocUnits = '';

RangeLwOut = Simulink.Parameter;
RangeLwOut.Value = [-1E-12; -1E-12; -1E-12];
RangeLwOut.HasCoderInfo = false;
RangeLwOut.Description = '';
RangeLwOut.DataType = 'auto';
RangeLwOut.Min = [];
RangeLwOut.Max = [];
RangeLwOut.DocUnits = '';

RangeUpEl = Simulink.Parameter;
RangeUpEl.Value = 1.5707963267948966;
RangeUpEl.HasCoderInfo = false;
RangeUpEl.Description = '';
RangeUpEl.DataType = 'auto';
RangeUpEl.Min = [];
RangeUpEl.Max = [];
RangeUpEl.DocUnits = '';

RangeUpIn = Simulink.Parameter;
RangeUpIn.Value = [1.0E+12; 1.0E+12; 1.0E+12; 1.0E+12; 1.0E+12; 1.0E+12; ...
                   1.0E+12; 1.0E+12; 1.0E+12; 1.0E+12; 1.0E+12; 1.0E+12; ...
                   ];
RangeUpIn.HasCoderInfo = false;
RangeUpIn.Description = '';
RangeUpIn.DataType = 'auto';
RangeUpIn.Min = [];
RangeUpIn.Max = [];
RangeUpIn.DocUnits = '';

RangeUpOut = Simulink.Parameter;
RangeUpOut.Value = [1.0E+12; 1.0E+12; 1.0E+12];
RangeUpOut.HasCoderInfo = false;
RangeUpOut.Description = '';
RangeUpOut.DataType = 'auto';
RangeUpOut.Min = [];
RangeUpOut.Max = [];
RangeUpOut.DocUnits = '';

Re = Simulink.Parameter;
Re.Value = 6.371E+6;
Re.HasCoderInfo = false;
Re.Description = '';
Re.DataType = 'auto';
Re.Min = [];
Re.Max = [];
Re.DocUnits = '';

doy_DAV = Simulink.Parameter;
doy_DAV.Value = 18;
doy_DAV.HasCoderInfo = false;
doy_DAV.Description = '';
doy_DAV.DataType = 'auto';
doy_DAV.Min = [];
doy_DAV.Max = [];
doy_DAV.DocUnits = '';

doy_DSAV = Simulink.Parameter;
doy_DSAV.Value = 6;
doy_DSAV.HasCoderInfo = false;
doy_DSAV.Description = '';
doy_DSAV.DataType = 'auto';
doy_DSAV.Min = [];
doy_DSAV.Max = [];
doy_DSAV.DocUnits = '';

k1 = Simulink.Parameter;
k1.Value = 0.92519;
k1.HasCoderInfo = false;
k1.Description = '';
k1.DataType = 'auto';
k1.Min = [];
k1.Max = [];
k1.DocUnits = '';

k10 = Simulink.Parameter;
k10.Value = 1.20556;
k10.HasCoderInfo = false;
k10.Description = '';
k10.DataType = 'auto';
k10.Min = [];
k10.Max = [];
k10.DocUnits = '';

k11 = Simulink.Parameter;
k11.Value = 1.41808;
k11.HasCoderInfo = false;
k11.Description = '';
k11.DataType = 'auto';
k11.Min = [];
k11.Max = [];
k11.DocUnits = '';

k12 = Simulink.Parameter;
k12.Value = 0.13985;
k12.HasCoderInfo = false;
k12.Description = '';
k12.DataType = 'auto';
k12.Min = [];
k12.Max = [];
k12.DocUnits = '';

k2 = Simulink.Parameter;
k2.Value = 0.16951;
k2.HasCoderInfo = false;
k2.Description = '';
k2.DataType = 'auto';
k2.Min = [];
k2.Max = [];
k2.DocUnits = '';

k3 = Simulink.Parameter;
k3.Value = 0.00443;
k3.HasCoderInfo = false;
k3.Description = '';
k3.DataType = 'auto';
k3.Min = [];
k3.Max = [];
k3.DocUnits = '';

k4 = Simulink.Parameter;
k4.Value = 0.06626;
k4.HasCoderInfo = false;
k4.Description = '';
k4.DataType = 'auto';
k4.Min = [];
k4.Max = [];
k4.DocUnits = '';

k5 = Simulink.Parameter;
k5.Value = 0.00899;
k5.HasCoderInfo = false;
k5.Description = '';
k5.DataType = 'auto';
k5.Min = [];
k5.Max = [];
k5.DocUnits = '';

k6 = Simulink.Parameter;
k6.Value = 0.21289;
k6.HasCoderInfo = false;
k6.Description = '';
k6.DataType = 'auto';
k6.Min = [];
k6.Max = [];
k6.DocUnits = '';

k7 = Simulink.Parameter;
k7.Value = -0.15414;
k7.HasCoderInfo = false;
k7.Description = '';
k7.DataType = 'auto';
k7.Min = [];
k7.Max = [];
k7.DocUnits = '';

k8 = Simulink.Parameter;
k8.Value = -0.38439;
k8.HasCoderInfo = false;
k8.Description = '';
k8.DataType = 'auto';
k8.Min = [];
k8.Max = [];
k8.DocUnits = '';

k9 = Simulink.Parameter;
k9.Value = 1.14023;
k9.HasCoderInfo = false;
k9.Description = '';
k9.DataType = 'auto';
k9.Min = [];
k9.Max = [];
k9.DocUnits = '';

lamGNP_deg = Simulink.Parameter;
lamGNP_deg.Value = -71.78;
lamGNP_deg.HasCoderInfo = false;
lamGNP_deg.Description = '';
lamGNP_deg.DataType = 'auto';
lamGNP_deg.Min = [];
lamGNP_deg.Max = [];
lamGNP_deg.DocUnits = '';

phiGNP_deg = Simulink.Parameter;
phiGNP_deg.Value = 79.74;
phiGNP_deg.HasCoderInfo = false;
phiGNP_deg.Description = '';
phiGNP_deg.DataType = 'auto';
phiGNP_deg.Min = [];
phiGNP_deg.Max = [];
phiGNP_deg.DocUnits = '';

phi_c1 = Simulink.Parameter;
phi_c1.Value = 16;
phi_c1.HasCoderInfo = false;
phi_c1.Description = '';
phi_c1.DataType = 'auto';
phi_c1.Min = [];
phi_c1.Max = [];
phi_c1.DocUnits = '';

phi_c2 = Simulink.Parameter;
phi_c2.Value = -10;
phi_c2.HasCoderInfo = false;
phi_c2.Description = '';
phi_c2.DataType = 'auto';
phi_c2.Min = [];
phi_c2.Max = [];
phi_c2.DocUnits = '';

sigma_c1 = Simulink.Parameter;
sigma_c1.Value = 12;
sigma_c1.HasCoderInfo = false;
sigma_c1.Description = '';
sigma_c1.DataType = 'auto';
sigma_c1.Min = [];
sigma_c1.Max = [];
sigma_c1.DocUnits = '';

sigma_c2 = Simulink.Parameter;
sigma_c2.Value = 13;
sigma_c2.HasCoderInfo = false;
sigma_c2.Description = '';
sigma_c2.DataType = 'auto';
sigma_c2.Min = [];
sigma_c2.Max = [];
sigma_c2.DocUnits = '';

