% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Mar-2022 10:55:33
%  MATLAB version: 9.10.0.1669831 (R2021a) Update 2
% -------------------------------------------------------------------
                                          

CheckOn = Simulink.Parameter;
CheckOn.Value = 1;
CheckOn.CoderInfo.StorageClass = 'Custom';
CheckOn.CoderInfo.Identifier = '';
CheckOn.CoderInfo.Alignment = -1;
CheckOn.CoderInfo.CustomStorageClass = 'Define';
CheckOn.CoderInfo.CustomAttributes.HeaderFile = 'Config.h';
CheckOn.Description = '';
CheckOn.DataType = 'uint8';
CheckOn.Min = [];
CheckOn.Max = [];
CheckOn.DocUnits = '';

